CHUNKING_VERSION = "v1_parent1800_child400_overlap20pct"

TOKENIZER_ENCODING = "cl100k_base"

PARENT_MAX_TOKENS = 1800
CHILD_MAX_TOKENS = 400
OVERLAP_RATIO = 0.20

PARENT_OVERLAP_TOKENS = round(PARENT_MAX_TOKENS * OVERLAP_RATIO)
CHILD_OVERLAP_TOKENS = round(CHILD_MAX_TOKENS * OVERLAP_RATIO)
